### PR TITLE
Update to classes

### PR DESCRIPTION
**Pull request by arthurvr**
Ref tastejs/todomvc-app-css#4

### CODE REVIEW

**Comment by samccone** [comment]
Can we chat about why we should do this? I know ID's are not ideal, but the amount of busy work this is going to generate for us to do is quite large... I would rather focus our energy on upgrading 100% of the UI's and then moving onto stuff like this.. thoughts?

**Comment by arthurvr** [comment]
> I know ID's are not ideal, but the amount of busy work this is going to generate for us to do is quite large...

Probably, yes, but the issue has been open since 2012 so probably time to do it :D Lately we were even seeing frameworks not being compatible with ids anymore, that's kind of a big deal.

> I would rather focus our energy on upgrading 100% of the UI's and then moving onto stuff like this.. thoughts?

If we're anyhow gonna migrate them all to `todomvc-app-css`, why not to do this directly?

**Comment by sindresorhus** [comment]
@samccone This is first and foremost for new apps. The more we defer this the more apps we'll have to upgrade ourselves in the future. The `todomvc-app-css` change got a major bump, so existing apps can upgrade whenever we have the resources for it. Just use the 1.0.0 version when switching to the new UI ;)

**Comment by sindresorhus** [comment]
> If we're anyhow gonna migrate them all to todomvc-app-css, why not to do this directly?

The UI upgrade is simple since there are almost no HTML changes. With the switch to classes a lot of the JS and logic will need updating which is an whole other nightmare to do at scale. Better to defer that to a separate task.

**Pull request merged**
